### ISSUE TITLE
rf不能训练

### ISSUE THREAD

**Issue by lihaicheng7003** [huang-sh/raatk#2]
clf_parser中有一处是不是错误呀，knn是不是应该改成rf

 rf = parser.add_argument_group('RF', description='Parameters for random forest classifier')
    rf.add_argument('-trees', '--n_estimators', type=int, default=100,
                        help='the number of trees in the forest, default=100')
    rf.add_argument('-features', '--max_features', default='auto',
                    help='the number of features to consider when looking for the best split,default=auto')
    **knn**.add_argument('-jobs','--n_jobs', type=int, default=1,
                            help='the number of jobs to run in parallel, default=1')
    rf.add_argument('-rs', '--random_state', type=int, default=1, help='random state,default=1')
    return parser

**Comment by huang-sh** [comment]
@lihaicheng7003  谢谢了，已更改。更新下再试试（pip install git+https://github.com/huang-sh/raatk.git@master -U）

**Comment by lihaicheng7003** [comment]
谢谢大佬。

Shenghui Huang <notifications@github.com> 于2020年12月10日周四 下午5:42写道：
